### ISSUE TITLE
在XCode7.0.1下,OAuthViewController.swift第65行有个报错: 'advance' is unavailable: call the 'advancedBy(n)' method on the index。

### ISSUE THREAD

**Issue by Gosicfly** [570262616/Weibo-Swift2.0#1]

**Comment by 570262616** [comment]
这个方法在xcode7.0.1中被修改了,暂时没有时间修改这个问题,sorry

**Comment by XYangX** [comment]
let code = query.substringFromIndex(query.startIndex.advancedBy("code".characters.count))

**Comment by pengting** [comment]
提示

"Request failed: bad request (400)" UserInfo={com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x7ff2dc3e3270> { URL: https://api.weibo.com/oauth2/access_token } { status code: 400, headers {
    "Cache-Control" = "no-cache";
    Date = "Wed, 04 Nov 2015 05:17:58 GMT";
    Expires = "Thu, 01 Jan 1970 00:00:00 GMT";
    Pragma = "No-cache";
    Server = "nginx/1.6.1";
    "api-server-ip" = "10.75.2.82";
} }, NSErrorFailingURLKey=https://api.weibo.com/oauth2/access_token, com.alamofire.serialization.response.error.data=<7b226572 726f7222 3a22696e 76616c69 645f6772 616e7422 2c226572 726f725f 636f6465 223a3231 3332352c 22726571 75657374 223a222f 6f617574 68322f61 63636573 735f746f 6b656e22 2c226572 726f725f 75726922 3a222f6f 61757468 322f6163 63657373 5f746f6b 656e222c 22657272 6f725f64 65736372 69707469 6f6e223a 22696e76 616c6964 20617574 686f7269 7a617469 6f6e2063 6f64653a 3d333137 32386462 35383964 62393934 32326530 33353534 62663637 31393238 37227d>, NSLocalizedDescription=Request failed: bad request (400)})
fatal error: unexpectedly found nil while unwrapping an Optional value
(lldb) 

这个是什么问题
